### ISSUE TITLE
Elastic search and findBy fields

### ISSUE THREAD

**Issue by harikt** [qandidate-labs/broadway#109]
Hi, 

I was searching via `findBy` method https://github.com/qandidate-labs/broadway/blob/41a495d69fba2303622febfb3bc715a0f500c61d/src/Broadway/ReadModel/ElasticSearch/ElasticSearchRepository.php#L91 and was not getting any results. 

```<?php
$fields = [
    'name' => 'beta',
];
$this->repository->findBy($fields)
```

I tried with plain elastic search api and results are getting for below api .

```php
<?php
$searchParams = array();
$searchParams['index'] = 'something';
$searchParams['type']  = 'Some\Namespaced\Class';
$searchParams['body']['query']['wildcard']['name'] = 'b*';
// $searchParams['body']['query']['match']['name'] = 'beta';
```

The find with id is working as expected.

Thanks!

**Comment by asm89** [comment]
@mbadolato When would these checks be run? Running them on each update operation would be quite expensive. We could add a default cli command to the bundle, but you'd still have to run it.

**Comment by wjzijderveld** [comment]
Closing this for now, as the issue was in Elasticsearch mapping.
The issue we have in Broadway is lack of good documentation...

**Comment by manelephant** [comment]
I can't solve this issue. Trying to set some field as "notAnalysedFields" using a class extending ElasticSearchRepository

 <service id="my_app.read_model.repository.card_overview"
                 class="MyApp\ReadModel\Repository\CardOverview">
        </service> 

Then using : 

        <service id="read_model.index_generator" class="MyApp\ReadModel\ElasticSearchIndexGenerator">
            <argument type="collection">
                <argument type="service" id="my_app.read_model.repository.card_overview" />
            </argument>
        </service>

But it keep crashing with this error : 

Catchable Fatal Error: Argument 1 passed to MyApp\ReadModel\Repository\CardOverview::__construct() must be an instance of Elasticsearch\Client,....etc

My class looks like this : 

class CardOverview extends ElasticSearchRepository
{
    public function __construct(
        Client $client,
        SerializerInterface $serializer,
        $index,
        $class,
        array $notAnalyzedFields = array('code')
    )
    {
        parent::__construct(
            $client,
            $serializer,
            $index,
            $class,
            $notAnalyzedFields
        );
    }
}

Is there something obvious for one of you guys ? Thanx :)
