### ISSUE TITLE
Renaming the add method on the AggregateRoot

### ISSUE THREAD

**Issue by wjzijderveld** [qandidate-labs/broadway#114]
Currently, you have to call the `add` method to save the uncommitted events of your aggregate root to the event store. it is called `add` because you add the events to the event store, but that name isn't very obvious when you want to save your aggregate.

Ideas for a better name are welcome!

**Comment by pminnieur** [comment]
I'd prefer `commit` since it appends the uncommitted domain events for the given aggregate root.

**Comment by davedevelopment** [comment]
:+1: for `commit`

**Comment by kimlai** [comment]
Are you talking about the `RepositoryInterface` ? If so, why not simply `save` ?

I don't think that the repository interface shoudl expose the fact that you have "uncommitted events" in your aggregate (that's an implementation detail linked to event soucing IMO).

And `commit` kinda sounds like you have transactions involved.

Just my two cents.

**Comment by MarkRedeman** [comment]
:+1: for `save`, same arguments as @kimlai .

**Comment by simensen** [comment]
:+1: for `save`, though `commit` would be acceptable as well.

I currently create my own repository interfaces and provide a Broadway EventSourcedRepository implementation. In my own interfaces, I'm using `save` and passing to `add`.

**Comment by mbadolato** [comment]
I'm currently using the default provided EventSourcedRepository but my command handlers contain a ```save()``` method that then passes off to the repository's ```add()```

**Comment by asm89** [comment]
Seems to me that renaming to `save()` is the way to go. If @wjzijderveld is :+1: as well I'd say we're happy for a PR (or we'll do it).

**Comment by cordoval** [comment]
:+1:

**Comment by harikt** [comment]
I was looking doctrine, and `flush` seems used. Any thoughts on it ?

**Comment by cordoval** [comment]
@harikt is totally another layer, one is a persistent transactional layer that has flush falvor, the other is not really that and i doubt it should that imo.

**Comment by davedevelopment** [comment]
Aye, following @kimlai's comments, `save` seems more appropriate, I hadn't even considered the interface, just the implementation.

**Comment by wjzijderveld** [comment]
Save would work for me as well :+1:

**Comment by pminnieur** [comment]
Fine with `save` :+1:

**Comment by asm89** [comment]
A PR for this would be great. :+1:

**Comment by mbadolato** [comment]
@asm89 I'll take it
