### ISSUE TITLE
Dropping branch alias

### ISSUE THREAD

**Issue by wjzijderveld** [qandidate-labs/broadway#123]
I like to drop the branch alias, it doesn't add much value with all the changes we do now and can cause pain when we forget to update it.

Another option would be to just change it to 1.x and don't look at it until we tag 1.0.0 :-)

Anybody against?

**Comment by harikt** [comment]
@wjzijderveld don't drop the alias. If you don't like change to `1.0.x` or something for the develop. So all who need develop can use `1.0.*@dev` .

**Comment by simensen** [comment]
What kind of pain does it cause? If it is things breaking for people because "BC breaks" happen and this reminds you to bump to the next minor version I think that is fine and to be expected.

:-1: on removing branch aliases as [dev-master is considered harmful](https://speakerdeck.com/simensen/composer-stability-and-semantic-versioning-demystified-nomad-php-eu-2014?slide=63).

**Comment by cordoval** [comment]
imo this is a byproduct of deifying-version-1 syndrome? :baby:

**Comment by wjzijderveld** [comment]
@simensen I indeed meant the part where people would use the branch alias and encounter BC breaks because we forget to update the branch alias.. 

I agree dev-master should be avoided. 

And what about bumping it to 1.x ?

**Comment by asm89** [comment]
@wjzijderveld We could bump it to `1.x`, though I'd personally like to see more early adapters using broadway in prod before we go to `1.x`.

The upside of using `0.x` branch aliases is that we've been nicely tagging `0.1`, `0.2` etc when we had a few changes (including BC breaks). The tags allow people to upgrade versions in bigger steps.

Not sure on this one. :)

**Comment by wjzijderveld** [comment]
I wouldn't mind keeping this branch alias structure for now, I just have to keep in mind that after tagging I must update the branch alias, which I tend to forget :smile:

**Comment by wjzijderveld** [comment]
Keeping it :)

**Comment by cordoval** [comment]
:+1:
