### ISSUE TITLE
Allow for multiple tables to be defined per BC/Aggregate

### ISSUE THREAD

**Issue by cordoval** [qandidate-labs/broadway#126]
currently the symfony commands are hardcoding the - %broadway.event_store.dbal.table% and it is only one, would be best to support multiple tables under a naming convention 1 per bc/or aggregate.

**Comment by wjzijderveld** [comment]
What is your use-case here?
Although not as easy as other stuff, you can create multiple event stores. Just add more service definitions (in case of the Symfony Bundle) with different table names and inject where needed. There is as far as I can see nothing stopping you from using multiple event stores.
