### ISSUE TITLE
answer this question please

### ISSUE THREAD

**Issue by cordoval** [qandidate-labs/broadway#131]
could you please answer @mbadolato question here in the link but answer it in this github thread

https://gist.github.com/wjzijderveld/dcd9a6478346182b287a

thanks cc @wjzijderveld

**Comment by cordoval** [comment]
i think i found the related explanation sort of here https://github.com/qandidate-labs/broadway/issues/109#issuecomment-68335644 onwards.

**Comment by mbadolato** [comment]
No, those are two completely unrelated things. #109 was discussing the indexing and non-analyzed fields for Elasticsearch. The gist is asking about logic in a sample piece of code used to actually generate an index for one specific model (as opposed to all indexes)

**Comment by wjzijderveld** [comment]
Commented:
We extend the ElasticsearchRepository for most of our repositories.
For repositories using the factory it won't work :disappointed:

**Comment by mbadolato** [comment]
Got it, thanks!

**Comment by cordoval** [comment]
hmm how is the extended class of the ElasticsearchRepository of yours look like that it solves the issue @mbadolato referred to? just curious. :baby: and for completeness sake. I will close but if you happen to be of a good heart you can paste the gist. Thanks!

**Comment by wjzijderveld** [comment]
The extended classes are usually just a constructor that define some of the
arguments for the base class.
And sometimes a method to do a specific query for that read model.
