### ISSUE TITLE
is there a way to dispatch several events or like a collection to reveal intention rather than one?

### ISSUE THREAD

**Issue by cordoval** [qandidate-labs/broadway#134]
usually one fires only one event, but more and more for my use case i am noticing i need to fire multiple events with more intention or that are `abstract` versions. Is there a method to fire these batch at once?

**Comment by wjzijderveld** [comment]
In what context do you need this? How would this be different from just firing the events in sequence, by calling `apply` multiple times in your AR?

**Comment by cordoval** [comment]
no difference. Closing :older_man: :sob:
