### ISSUE TITLE
Serialization Problems

### ISSUE THREAD

**Issue by Richtermeister** [qandidate-labs/broadway#138]
Hi all, 

I'm loving this framework, great job! One issue I am struggling with is the serialization of event payloads.
Some of our events carry Value Objects, and they get lost in serialization. Further, the current SerializerInterface works with arrays, even though serialization implies strings.. this makes it difficult to integrate more mature solutions which also want to work with string.

I suspect that your reasoning behind the array format is opportunity for backwards compatibility if event code evolves away from already recorded events.. is this the case?

Thank you for any help understanding this better.
Daniel

**Comment by cordoval** [comment]
https://github.com/qandidate-labs/broadway/blob/master/src/Broadway/Serializer/SerializerInterface.php#L15-L16

It seems this was not built to support objects but scalars. Perhaps that can clarify the question.

I am also interested if this was done for elasticsearch, why the interface was forced to that and not support objects underneath the serialization output?

**Comment by cordoval** [comment]
I think also in https://github.com/qandidate-labs/broadway/blob/master/src/Broadway/Domain/Metadata.php#L50 when it gets serialized and the information accessible as an array then is a bit misleading. Maybe there should be a note somewhere in the docs about acknowledging that the concept of serialization is not to strings but to arrays because of elastic search and for practical reasons which would be good to list.

**Comment by cordoval** [comment]
one more reason to tag the package to include the metadata accessing fix on projector land from @mbadolato !  :older_man:

**Comment by wjzijderveld** [comment]
@Richtermeister thanks for the compliment :smile: 

I wasn't involved from the start, so I don't know about all the design decisions. But I'm guessing serializing to flat array is just convenient. In the end it gets saved as json in the database, which is a lot easier with arrays :-)

How we handle value object, is by calling the serialize method on those objects:

```php
class Foo {
  private $stringProperty;
  private $valueObject;

  public function serialize() {
    return array(
      'stringProperty' => $this->stringProperty,
      'valueObject'    => $this->valueObject->serialize()
    );
  }
}
```

And with deserializing we reconstuct the value objects. Which usually is just instantiating it, as all properties are part of the constructor in our case.

**Comment by wjzijderveld** [comment]
@Richtermeister I'm closing this for now, if you have any further questions, please re-open or ask in our IRC channel (#qandidate on Freenode)
