### ISSUE TITLE
do broadway listeners have priority?

### ISSUE THREAD

**Issue by cordoval** [qandidate-labs/broadway#143]
why and why not?

**Comment by mbadolato** [comment]
What is your use case?

**Comment by cordoval** [comment]
i was just curious since symfony event listeners do have priority if that thing works in broadway too or if there is any thing like that similar or any usage.

**Comment by mbadolato** [comment]
I don't really know that there's a need for one without specific use cases. The listeners are projectors and processors so I don't know that a priority is really of any use

**Comment by cordoval** [comment]
yeah I guess we don't have a use case really. Closing then, big thanks :+1: :older_man: you are the saga :8ball:

**Comment by francescotrucchia** [comment]
In my use case I need to send an email after an event is dispatched. In the email I need some information created after a projection handle by the same event. In my case have a priority could be useful

**Comment by wjzijderveld** [comment]
@francescotrucchia That is in the nature of eventual consistency. There is no promise which projector or processor get's the event first. There are quit some good resources about this: https://www.google.nl/search?q=event+sourcing+eventual+consistency

**Comment by codeliner** [comment]
@francescotrucchia In addition to the eventual consistency topic you may need a process manager aka Saga when your email depends on information created by a projection

**Comment by francescotrucchia** [comment]
@wjzijderveld @codeliner thanks for suggestions :+1:

**Comment by francescotrucchia** [comment]
@wjzijderveld I understand the problem of eventual consistency, but in an environment request/response where the process are synchronous I think that the ventual consistency doesn't exists and in this case could be more pragmatic using the priority on listener.

**Comment by codeliner** [comment]
@francescotrucchia I can follow your argument, but eventual consistency depends on the transaction boundary not on PHP's request/response environment.
