### ISSUE TITLE
second bus projector via tags?

### ISSUE THREAD

**Issue by cordoval** [qandidate-labs/broadway#144]
So I am having to create projectors that really fire a second command depending on some conditions.

They act as a second layer on top of my microservices aka BCs. 

So my question is if projectors that act on replaying/rebuilding need to be called also, this seems like they will create double the events that they were firing.

Broadway does not seem to have examples or implementations for these cases? any insights cc @simensen  @mbadolato  @wjzijderveld would be appreciated

**Comment by simensen** [comment]
@cordoval I believe you might be looking for a Processor.

https://github.com/qandidate-labs/broadway/blob/master/src/Broadway/Processor/Processor.php

**Comment by cordoval** [comment]
so the Processor already does this division cc @simensen @mbadolato ?

It seemed to me that we were using them indistinctly on broadway examples?

**Comment by simensen** [comment]
I'm not sure about the examples, but from what you are describing it sounds similar. Basically, a process that acts on events that is not itself a Projector. Someone else can weigh in, too, as I could be wrong on this. I haven't used them yet myself.

**Comment by mbadolato** [comment]
Yeah my guess is you're looking for a saga or processor. There are currently no examples in the broadway repo for them

**Comment by cordoval** [comment]
yeah processors are the way, thanks guys :older_man:
