### ISSUE TITLE
Component to replay event streams to event bus

### ISSUE THREAD

**Issue by cyberwolf** [qandidate-labs/broadway#148]
It would be nice to have a component that can replay all events from an event store (in historical order) to an event bus. This would facilitate a few use cases, like:
- correcting faulty read models
- initialize new read models

We've already coded a callable class EventStream specific for DBAL (https://github.com/cultuurnet/udb3-php/commit/9af9770ca1bfa3976f977f802cb85a0f05d0132f) which returns a PHP Generator for iterating over all stored events in the right historical order, and it's used in a CLI command in our SIlex application (https://github.com/cultuurnet/udb3-silex/blob/feature/event-stream-replay/src/Console/ReplayCommand.php#L47). Unfortunately we had to copy quite some code from the DBAL EventStore to our class. Splitting up some methods like deserializeEvent() from the DBALEventStore to a separate class might be a good idea, or the EventStore interface itself could be extended to allow to retrieve all events. There are several possibilities. I'd be happy to discuss this a bit more with you.

**Comment by mbadolato** [comment]
I have one that I created for a prototype a while back and a few people have used it. It requires a slightly modified EventStore class with a method that allows you to fetch all IDs from the event store, then replay each stream.

Both classes are [here](https://gist.github.com/mbadolato/7a66bfe6480977009af7). The ```IdRetrievableDBALEventStore.php``` class just takes the Broadway ```DBALEventStore.php``` class as an argument and pushes all other functions to that class.

**Comment by nWidart** [comment]
Indeed, I've managed to use the class from @mbadolato ,slightly modified for laravel integration. Though it would be nice to have it built in Broadway. Since replaying events is one of the main ideas of event sourcing... (something that EventStore does, by default)

**Comment by mbadolato** [comment]
> Though it would be nice to have it built in Broadway

I did have a brief discussion with @wjzijderveld about that back when I created the class and at the time he wasn't sure replaying the projections was capability that needed to be in Broadway itself. Perhaps it's time to revisit that topic as an independent discussion with the @qandidate-labs team and the community?

**Comment by cyberwolf** [comment]
@mbadolato , thanks for sharing! For very large amounts of entities though, the approach of first fetching all unique entity IDs will be quite memory-consuming. Also, events are sent out of their historical order to the event bus, so read model projectors that count on events arriving in the right order might get produce the wrong data.

**Comment by nWidart** [comment]
@mbadolato Yeah I remember something about that on IRC. But I still don't get why it's not in Broadway. Every single talk of Greg Young talks about replaying events, as one of the main benefits of event sourcing. And Broadway doesn't offer that **huge** benefit.

**Comment by wjzijderveld** [comment]
The reason why we aren't sure if it should be part of Broadway, is because of the fact that there are to many use-cases too consider. 

Sometimes you want to replay events just for the projectors to rebuild you read model. Sometimes you want to replay events to generate a new kind of report. Sometimes you want to replay because some processor crashed. etc.

All those use-cases have different requirements and a lot of time you still need some custom code for your application (maybe just configuration wiring, maybe more).

What probably is possible, is to have more tools to retrieve (specific) events. There is already a PR that addresses that: https://github.com/qandidate-labs/broadway/pull/73 But that is on hold at the moment. 
In my opinion that is a good start to look at replaying of events.
At Qandidate.com we also have some solutions for replaying, but they are all custom made for our purposes (also because of time pressure). We might be able to share (some of) those. 

I really hope to be able to make some time in the coming weeks to help get stuff like this going again. I have been swamped until recent and this week I was sick at home.. I hope to be able to make more quality time for OSS again.

**Comment by mbadolato** [comment]
> For very large amounts of entities though, the approach of first fetching all unique entity IDs will be quite memory-consuming.

@cyberwolf Oh, most likely; As I said, the linked script was for a prototype I was working on and I just needed something to work with the very limited data set I was using :smile:

**Comment by cyberwolf** [comment]
@wjzijderveld Thanks for your insightful reply and the link to PR 73. Tools to retrieve specific events would indeed be a good basis for whatever kind of replay. I'm not sure at this point that using the visitor pattern for this purpose is a good idea, I might need to take a closer look at AxonFramework to understand the merits.

**Comment by philbates35** [comment]
Hi,

A related question - does anyone have any advice, or an example implementation, of how I could use Broadway's components to replay the event store and rebuild the projections? Right now I'm not bothered about special use cases and retrieving subsets of events (as mentioned above), I just want to replay the whole history to rebuild every projection whenever I need to.

I imagine the process would go something like:
1. Empty the read model repository (so in Elastic search delete every index)
2. Subscribe all projectors to the event bus (as an aside - in the future, it might be nice to be able to specify a subset of projectors to subscribe for a given rebuild - maybe defining a rebuild configuration with an alias could be an idea. But let's not worry about that for now.)
3. Retrieve all events from the event store
4. Loop through all events, and publish each one in the event bus.

I think that's a good starting point, but the bit I'm struggling with is the initial step 1. of emptying of the read model repositories - as `Broadway\ReadModel\RepositoryInterface` doesn't have a `empty()` or `clear()` method, it's not possible for me to empty the table myself using a `RepositoryInterface`.

Does it seem to you guys that an additional `empty()` method, or similar, is needed to be added to `Broadway\ReadModel\RepositoryInterface` to to able to delete everything and start again? From the comments it seems like people have found ways to rebuild their projections - how are you handling the emptying of your read model repositories?

Any general read model advice, help or examples would be very welcome. :)

**Comment by tudobala** [comment]
@philbates35, this is what I use to empty my read models:

```php
<?php
require __DIR__.'/vendor/autoload.php';
use Elasticsearch\Client;
$es = new Client();
if ($es->indices()->exists(['index' => 'yourIndexName'])) {
    $es->indices()->delete(['index' => 'yourIndexName']);
}
```

**Comment by mbadolato** [comment]
@philbates35 I have a sample (Symfony-based) one that I used for a prototype and a few people have used it as a starting point. It is [here](https://gist.github.com/mbadolato/7a66bfe6480977009af70) and includes a modified DBALEventStore implementation allowing for getting all unique ids in the event store, then retrieveing and playing each stream.

I also have a gist with a few files comprising a create index (elasticsearch) [here](https://gist.github.com/mbadolato/885211c8a5c3682290cc) and you would just do something similar to create a delete index.

Hope that helps as a starting point!

**Comment by philbates35** [comment]
@tudobala thanks. You're right that works, but you're referencing Elasticsearch client directly rather than using the `RepositoryInterface` that the package provides that currently I'm using throughout my application (in the same way that the official Qandidate example Broadway application only references the interface throughout the application).

**Comment by philbates35** [comment]
@mbadolato the link to your example symfony app seems to be broken. I had a quick look through your GitHub repos but couldn't seem to find a Broadway application.

Re your gist - I like it a lot and will probably end up doing something like that myself. But as I mentioned in my previous message, that's all Elasticsearch specific, rather than using interfaces.

In my application I've configured my container to inject the correct instance of `RepositoryInterface` when needed throughout my application. So I am always typing hinting `RepositoryInterface` in constructor arguments. In the console command I want to create to empty and rebuild the read model, I ideally only want to only talk to instances of `RepositoryInterface` without having to worry if it's Elasticsearch, MySQL, in memory or whatever.

I realise I'm being a bit pedantic, and I'll almost certainly always use forever Elasticsearch (never switching out the implementation) and your proposed solutions will work fine. However it would be great if Broadway's `RepositoryInterace` chould cater for this scenario, so I don't have to talk to the implementation directly in some circumstances.

**Comment by mbadolato** [comment]
@philbates35 Whoops, link fixed. Sorry, extra character got added to the end of the URL. Re: Elasticsearch specific. Yep, as I mentioned these were from a prototype and are not full solutions. The sample code in my gists were so others could see a basic implementation when I was prototyping. They're just a starting point for you. Also you will not see a full Symfony app in the links, they're just a couple of classes and the service definitions

**Comment by tudobala** [comment]
@philbates35,

I don't think you are being pedantic at all and I agree with you. But I believe that clearing of the read model seems more like a tool/maintenance thing, when things go wrong, or for testing. Basically along the lines that the operation might not be executed often in production, thus not needing to be forced to be implemented RepositoryInterface. I would be very upset if someone in my team called a clear() on the repo hehe...

**Comment by philbates35** [comment]
@tudobala you do make a valid point, but I still think that there should be someway to be able to talk to interfaces configured in my containing and still be able to clear out a table, even if it isn't talking to a `RepositoryInterface`.

One idea that comes to mind is that we keep `RepositoryInterface` only concerned with querying, as it is now (so no changes there), and create a new `ReadModelSchemaManagerInterface` (or similar name) that is responsible for adding/dropping tables/indexes, and anything else do do with manipulating the schema.

```php
interface ReadModelSchemaManagerInterface
{
    /**
     * Creates a new schema with the given name.
     * 
     * @param string $schema
     */
    public function create($schema);

    /**
     * Empties out the provided schema.
     *
     * @param string $schema
     */
    public function empty($schema);

    /**
     * Removes entirely the provided schema.
     *
     * @param string $schema
     */
    public function drop($schema);
}
```

The Elasticsearch implementation would look like:

```php
use Elasticsearch\Client;

class ElasticsearchReadModelSchemaManager implements ReadModelSchemaManagerInterface
{
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /**
     * Creates a new schema with the given name.
     * 
     * @param string $schema
     */
    public function create($schema)
    {
        // This should be what is now ElasticSearchRepository::createIndex()
    }

    /**
     * Empties out the provided schema.
     *
     * @param string $schema
     */
    public function empty($schema)
    {
        // I'm sure there's a better way to do this, but for the sake of example:
        $this->drop($schema);
        $this->create($schema);
    }

    /**
     * Removes entirely the provided schema.
     *
     * @param string $schema
     */
    public function drop($schema)
    {
        // This should be what is now ElasticSearchRepository::deleteIndex()
    }
}
```

That way, the repositories can't doing anything terrible like accidentally drop the whole index/table, but you do have the ability to drop the tables/indexes when needed by talking to the `ReadModelSchemaManagerInterface`.

At least to get the ball rolling, does this seem like a good idea to anyone?

**Comment by wjzijderveld** [comment]
I don't have the time to response in a very elaborate way, but I'd like to jump in :smiley: 

In my opinion Broadway shouldn't be to much concerned with the read models. The limited amount of tools you have available now are nice to get started, to have a simple way to start playing with event sourcing and CQRS. But they were never meant to be a drop-in solution for all read models. 

To be honest, at this moment I am more tempted to remove read model support completely from Broadway. As it's not something we want to provide an extended abstraction layer for.
Each storage has it's different restrictions and needs to be handled differently, so having an abstraction layer that tries to cover RDBMS, Document Databases, GraphDatabases, Key-Value Storage etc is just asking for trouble :see_no_evil: 
The same goes for replaying as well, replaying a read model in MySQL is different from replaying to Elasticsearch.

If I have some time left this afternoon I can share something we cooked up in the last few weeks, where we make a projector responsible for the replaying.

**Comment by tudobala** [comment]
@wjzijderveld,

I have the same thoughts as yours. Also, on my code that does read model/elasticsearch queries, I found it easier and more flexible to call the ES Client directly to submit the queries, rather than use the Broadway implementation. Even for generating the not_analyzed indexes for read model IDs I am doing it outside with an external PHP script.

**Comment by philbates35** [comment]
@wjzijderveld thanks for your response. Okay then, so I conclude from your response that you think it would be a good idea to pretend the read model components don't exist (treat them a basic example, but don't use them) and configure my own read model architecture. When you put it that way, it makes a lot of sense.

Also, I would be very much interested in seeing how you made a projector responsible for replaying, if you have the time to share.

Thanks. :)

**Comment by wjzijderveld** [comment]
@philbates35 

This is something we build recently, we haven't even run this in production yet.
We haven't designed this to handle all cases, but I think it can be used for quit some cases. 
In the postReplay you could switch aliases for example when using elasticsearch, so you could project something in a new index during replay, and after replay swap the aliases. But again, just an example, I don't believe in a perfect solution concerning replaying.

https://gist.github.com/wjzijderveld/b8bd5fd748fca8c0bc58

**Comment by philbates35** [comment]
@wjzijderveld That's a really interesting way to go about it. I've now implemented something very similar in the experimental application I'm working on and I'll see how it works out.

Thanks for taking the time to put that together :)

**Comment by wjzijderveld** [comment]
I'm going to close this for now. With the query possibility the event-store now has, writing a solution in your own application is quit trivial.

As shown in the gist above there might be something we can put into Broadway at some point,
