### ISSUE TITLE
Laravel has more github stars then Symfony

### ISSUE THREAD

**Issue by xtrasmal** [qandidate-labs/broadway#160]
.. :D hello everybody

Just saying..but could we work on the Laravel package that is under the broadway git namespace?
It's really great stuff.

**Comment by Ocramius** [comment]
I was also thinking that sugar is sweeter than salt.

Makes you think...

**Comment by tPl0ch** [comment]
Wow, very Laravel, much stars, such framework...

**Comment by xtrasmal** [comment]
![Haters gonna hate](http://vignette1.wikia.nocookie.net/academicjobs/images/9/98/Haters-gonna-hate.gif)

**Comment by cordoval** [comment]
@wjzijderveld could you please close and block this thread, laravel can be discussed in their crappy repositories

**Comment by xtrasmal** [comment]
I'll close this, but don't be a hater. The "more stars" bladibla was ment in a fun way.

**Comment by wjzijderveld** [comment]
@xtrasmal I'm not sure what you meant. There is a laraval package (link is in the readme), but (at least for now) it won't be in Broadway itself. Mainly because I don't feel like maintaining it. 

Threads with cool gifs are always fun :-)

**Comment by mbadolato** [comment]
@xtrasmal There already is a Laravel integration package that @nWidart built (see the README for Broadway)

@cordoval "their crappy repositories"? Why the disparage?

**Comment by cordoval** [comment]
just retorting it in a funny way :older_man:

**Comment by xtrasmal** [comment]
@wjzijderveld Dankje
@mbadolato Thank you for the info. 
@cordoval Try not to react like a caveman. We're too old to act like fanboys. We're software developers that love to craft great code. You probably had a bad day, so sorry to have triggered that emotional reaction.

Again thanks everybody. I'll have a look.

**Comment by nWidart** [comment]
Feedback welcome on the Laravel package by the way. :smiley:

**Comment by xtrasmal** [comment]
@nWidart I will definitely try it out. I'd like to use broadway for my symfony and laravel projects. :dancer:

**Comment by cordoval** [comment]
@xtrasmal I am having a good day, was sending some PRs internally before you start parading about laracrap. :blush:

**Comment by asm89** [comment]
Locking this as I don't like where this thread is going.

@xtrasmal It'd be great if you can work with @nWidart on improving the Laravel package. :+1: Feel free to ping me (and @wjzijderveld?) on issues that arise.
