### ISSUE TITLE
Unable to override apply function

### ISSUE THREAD

**Issue by aryou** [qandidate-labs/broadway#161]
Unable to override Broadway\EventSourcing\EventSourcedAggregateRoot::apply function because of private class properties. Need this functionality to add Metadata to the domain message

**Comment by mbadolato** [comment]
Can you explain a bit more about what you're trying to do? Domain messages get Metadata added to them via decoration. You can take a look at [this](https://github.com/qandidate-labs/broadway/issues/61) thread and see the procedure outlined when I was working out how to accomplish the task (2nd post in the thread)

**Comment by wjzijderveld** [comment]
Closing this for now. I understand where you run into, but I'd like to see more use-cases before implementing a fix. 
Please re-open if you have more info on how you'd like to see this.
