### ISSUE TITLE
Implement changes for Symfony 2.7+3.0

### ISSUE THREAD

**Issue by wjzijderveld** [qandidate-labs/broadway#166]
Symfony added deprecated warnings, which cause our tests to fail.
We can try to just ignore them, by adjusting error_reporting, but as we want to keep supporting 2.3 and later on 3.0, it might be better to fix it now.

I haven't looked in details to all warnings, but it mostly seems related to service definitions using `factory-method`.
An idea we had, is to split some of the service definitions into separate files, and load the appropriate file from the `BroadwayExtension`. 
We can use imports to share definitions that aren't affected by the deprecation warnings.

**Comment by ged15** [comment]
https://github.com/qandidate-labs/broadway/pull/167

**Comment by qooplmao** [comment]
For the `factory`/`factory-[service|method]` issue could you not do like a lot of others have done and moved that part into the Extension for the time being? Then when support is dropped for 2.3 move the definitions back into the individual config files.

For example...

```php
$definition = $container->getDefinition('broadway.saga.state.mongodb_database');

// Required until support for 2.3 dropped
if (method_exists($def, 'setFactory')) {
    $definition->setFactory(array(
        new Reference('broadway.saga.state.mongodb_connection'),
        'selectDatabase'
    ));
} else {
    $definition->setFactoryService('broadway.saga.state.mongodb_connection');
    $definition->setFactoryMethod('selectDatabase');
}
```

**Comment by mvriel** [comment]
Just ran into this when trying to use Broadway in Symfony 3:

```

  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
  Unable to parse file "/vendor/broadway/broadway/src/Broadway/Bundle/BroadwayBundle/DependencyInjection/../Resources/config/saga/mongodb.xml".



  [InvalidArgumentException]
  [ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', attribute 'f
  actory-service': The attribute 'factory-service' is not allowed. 
  [ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', attribute 'f
  actory-method': The attribute 'factory-method' is not allowed. 
  [ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', attribute 'f
  actory-service': The attribute 'factory-service' is not allowed. 
  [ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', attribute 'f
  actory-method': The attribute 'factory-method' is not allowed. 
````

**Comment by qooplmao** [comment]
The `factory-service`/`factory-method` setup was changed to the `factory` tag mid December with [this commit](https://github.com/qandidate-labs/broadway/commit/ab1fe3cc5aaa189eac8f64042ed98d0f450e8ed7) but it only seems to be available in `dev-master` at this point so I would recommend using that.

**Comment by mvriel** [comment]
Thanks for the tip!

**Comment by othillo** [comment]
solved by https://github.com/qandidate-labs/broadway/pull/228
