### ISSUE TITLE
timeOfOcurrence support

### ISSUE THREAD

**Issue by cordoval** [qandidate-labs/broadway#169]
when i replay events I find myself hunting for the time when the event actually occurred so that say fields like updatedAt on certain object are given this time rather than \DateTime('now'), is this perhaps something this library can help with in terms of providing say (if this is a correct  approach) a trait or some of the sorts?

:older_man:

**Comment by cordoval** [comment]
i guess just using the recordedOn from message

**Comment by Ocramius** [comment]
@cordoval isn't this usually what you'd store in the metadata via decoration/enrichment?

**Comment by cordoval** [comment]
right, the recordedOn on the domain message in this case
