### ISSUE TITLE
ramsey/uuid is dead can i send a PR changing this?

### ISSUE THREAD

**Issue by cordoval** [qandidate-labs/broadway#170]

**Comment by mbadolato** [comment]
Dead how?

https://github.com/ramsey/uuid

**Comment by wjzijderveld** [comment]
Why do you think it's dead?

**Comment by mbadolato** [comment]
It was changed over from ```rhumsaa/uuid``` a while ago, but the Broadway repo already reflects that change

**Comment by cordoval** [comment]
nevermind i was using and old version sorry :+1:

**Comment by cordoval** [comment]
lack of tags mislead me :blush: sorry, i am now on dev-master@dev

**Comment by cordoval** [comment]
@mbadolato https://github.com/qandidate-labs/stack-request-id/issues/2 it seems not all packages have been updated which creates really a big headache :sob:
