### ISSUE TITLE
Unittest require_once

### ISSUE THREAD

**Issue by thierryve** [qandidate-labs/broadway#183]
Hi,

First of all this is a great project. 
Today I clone the repo to have a better look. When running the unit test an error occured.
```
PHP Fatal error:  Call to a member function add() on boolean in /var/www/broadway/test/bootstrap.php on line 14

Fatal error: Call to a member function add() on boolean in /var/www/broadway/test/bootstrap.php on line 14
```
So I looked it up and it turns out require_once returns a boolean not the content.
http://stackoverflow.com/questions/26257846/why-i-cannot-get-the-return-value-of-require-once-function-in-php

I changed require_once to require and everthing worked as expected.
I'm using php 5.6.

**Comment by wjzijderveld** [comment]
Did you by any chance added phpunit to composer.json? That's the only case I know of how this happens. 

I opened #184 to fix this.

**Comment by thierryve** [comment]
Yes I added phpunit in composer.json an ran the test via vendor/bin/phpunit.

Thnx for the quick fix
