### ISSUE TITLE
Doctrine MongoDB is now a requirement

### ISSUE THREAD

**Issue by JurJean** [qandidate-labs/broadway#197]
After getting the new version 0.7, doctrine mongodb seems to be a requirement:

Fatal error: Class 'Doctrine\MongoDB\Connection' not found in /data/app/cache/dev/appDevDebugProjectContainer.php on line 644

If this was intentional, doctrine-mongodb should be moved from require-dev to require in composer. Otherwise, it should be handled correctly in the DI container.

**Comment by asm89** [comment]
Sounds like a regression to me.

**Comment by asm89** [comment]
@JurJean Would you mind gisting that line and the surrounding lines from your dumped container?

**Comment by JurJean** [comment]
Sure here it is:
https://gist.github.com/JurJean/f1ab179796b2ff90d9e8

**Comment by wjzijderveld** [comment]
@JurJean Are you able to try the fix in dev-master? I'm pretty sure this fixed it, but would like to know if you still have issues before I tag 0.7.1 :)

**Comment by JurJean** [comment]
Yes it works! Thanks!

**Comment by wjzijderveld** [comment]
Thanks for you quick response!
Tagged 0.7.1
