### ISSUE TITLE
Recording (current) user responsible for issuing Command

### ISSUE THREAD

**Issue by tudobala** [qandidate-labs/broadway#208]
How would I go about recording which user was responsible for generating a Domain Event? For example, a super admin changes another user's password.

I see two possible ways to achieve this:

1) Inside the Domain Event DTO (let's say ChangePasswordEvent), add a property to hold the UUID of the user that was responsible for the event. But in every single event I want to log this information (all events really), I would have to do the same.
OR
2) Add the information in the metadata that is created along the DomainEvent object

Any ideas?

**Comment by mbadolato** [comment]
In this case I would probably go with option 2. 

Unless the user id is something that is specifically required as part of the domain and the command/event your issuing, the id doesn't really belong as part of the event in option 1.

Using the enrichers and having the issuing user available in the metadata means you set that up once and you have the data available in all of your events and can log the info for each event that requires it.

**Comment by Xerkus** [comment]
I suppose it will require command metadata to have that information too, so it can propagate to events. But what about commands issued by saga, for example?

**Comment by mbadolato** [comment]
Commands don't have to know anything about that data. The Metadata enrichers automatically decorate the events and store the created metadata in the events table, and make them accessible as part of the domain message (in projectors for instance). So you just need to create and wire up the enricher(s) and the data will then be stored with the events.

If you look in the repo's Broadway bundle, there's a sample enricher there so you can see how it works. I'm not in a position today to dig out some separate code but probably can on monday

**Comment by wjzijderveld** [comment]
As @mbadolato said, it will depend on your domain requirements.

What we do at Qandidate.com is something like [this gist](https://gist.github.com/wjzijderveld/3067dd96b3f3c902548f).

That enricher is added to the [`MetadataEnrichingStreamDecorator`](https://github.com/qandidate-labs/broadway/blob/6fb01e9dc1301e7b932c5798f61fc00ed7660107/src/Broadway/EventSourcing/MetadataEnrichment/MetadataEnrichingEventStreamDecorator.php) in the service definition by adding the tag `broadway.metadata_enricher` (as we use Symfony):

```xml
<service id="acme.metadata_enricher.security" class="Qandidate\AcmeBundle\MetadataEnricher\SecurityMetadataEnricher">
    <argument type="service" id="security.context" />
    <tag name="broadway.metadata_enricher" />
</service>
```

We also have a second enricher that adds request information (IP and unique request id).

This way the information is saved with each event, so you don't have to keep track of this information for each event you are recording.
But the information isn't actually part of the event itself, so you can't depend on it being available in every domain event listener.

**Comment by Xerkus** [comment]
@mbadolato what i don't understand is where that data comes from? Considering command is not necessary handled in same process it issued.

**Comment by mbadolato** [comment]
@Xerkus It comes from the enrichers. Let's say you have a Symfony project (sorry, that's the only way I can relate this info) and you want to store metadata containing the username of the logged in user (or in our case, 'System' when there is no logged in user that fired a command because it was done from a command line process.

Configuration is done via the standard Symfony configuration system. I use a separate ```metadata_enrichers.xml``` file

```xml
<?xml version="1.0" encoding="UTF-8" ?>

<container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

    <services>
        <service id="metadata_enricher.username" class="Path\To\MetadataEnrichment\UsernameMetadataEnricher">
            <argument type="service" id="security.token_storage" />
            <tag name="broadway.metadata_enricher" />
        </service>
    </services>
</container>
```

That configures the following class. Notice that Symfony's security token storage service has been injected:

```php
<?php

namespace Path\To\EventSourcing\MetadataEnrichment;

use Broadway\Domain\Metadata;
use Broadway\EventSourcing\MetadataEnrichment\MetadataEnricherInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

final class UsernameMetadataEnricher implements MetadataEnricherInterface
{
    private $tokenStorage;

    public function __construct(TokenStorageInterface $tokenStorage)
    {
        $this->tokenStorage = $tokenStorage;
    }

    public function enrich(Metadata $existingMetadata)
    {
        $username = $this->tokenStorage->getToken() ? $this->tokenStorage->getToken()->getUsername() : 'System';
        $metadata = new Metadata(['user' => $username]);

        return $existingMetadata->merge($metadata);
    }
}
```

As an event is ```apply()``ed in Aggregate Roots, Broadway will decorate each event. It calls out to the metadata enricher(s) and execute each enricher's code, creating the ```Metadata``` object. That metadata is then applied to the event as the event is published, and gets stored in the event store in the metadata columns.

**Comment by rjkip** [comment]
@Xerkus wrote:

> @mbadolato what i don't understand is where that data comes from? Considering command is not necessary handled in same process it issued.

If the command is processed in another process, there's probably no other effective way than to send the metadata (the authenticated user in this case) with the command. You can either include it in the command, or have separate metadata.

Now I don't know what your situation exactly is, but I have the feeling the following suggestions will help you. Some things may apply to Symfony2 projects only, but the principle described here should be clear.

In an ES project I have worked on there are, among other applications, the Self-Service and Middleware applications. The Middleware handles commands sent by the Self-Service. The Self-Service [always adds the currently authenticated user (actor) to all commands](https://github.com/SURFnet/Stepup-SelfService/blob/b32c47ea62457c787e03f8c0aa8e39214f39839b/src/Surfnet/StepupSelfService/SelfServiceBundle/Service/CommandService.php#L48-L57) sent to the Middleware using a [decorator](https://en.wikipedia.org/wiki/Decorator_pattern).

The JSON payload sent to the Middleware looks a lot like the following:

```json
{
    "command": { "name": "AppCommand", "payload": 42 },
    "metadata": { "actor": "de305d54-75b4-..." }
}
```

The Middleware, [on receipt](https://github.com/SURFnet/Stepup-Middleware/blob/8db343c2c8970d458fb74df734cd2421b2465228/src/Surfnet/StepupMiddleware/ApiBundle/Controller/CommandController.php#L35) of the command, stores the actor (authenticated user) in our [metadata enricher](https://github.com/SURFnet/Stepup-Middleware/blob/8db343c2c8970d458fb74df734cd2421b2465228/src/Surfnet/StepupMiddleware/ApiBundle/Controller/CommandController.php#L44-L45). The metadata enricher in turn [adds the metadata](https://github.com/SURFnet/Stepup-Middleware/blob/8db343c2c8970d458fb74df734cd2421b2465228/src/Surfnet/StepupMiddleware/CommandHandlingBundle/EventSourcing/MetadataEnrichingEventStreamDecorator.php#L52-L56) to any recorded events.

Good luck!

**Comment by tudobala** [comment]
Thank you @mbadolato, @Xerkus, @wjzijderveld and @rjkip

I ended up using the [MetadataEnrichingEventStreamDecorator (from broadway)](https://github.com/qandidate-labs/broadway/blob/6fb01e9dc1301e7b932c5798f61fc00ed7660107/src/Broadway/EventSourcing/MetadataEnrichment/MetadataEnrichingEventStreamDecorator.php) and adding a MetadataEnricher with the user info to it, as @mbadolato and @wjzijderveld proposed.

@rjkip, is there any special reason why you are implementing your own [MetadataEnrichingEventStreamDecorator (from SURFnet)](https://github.com/SURFnet/Stepup-Middleware/blob/8db343c2c8970d458fb74df734cd2421b2465228/src/Surfnet/StepupMiddleware/CommandHandlingBundle/EventSourcing/MetadataEnrichingEventStreamDecorator.php)?

**Comment by rjkip** [comment]
@tudobala I don't remember the rationale behind this. It may as well have been an oversight and a `MetadataEnricher` would have done fine. :grinning:

**Comment by tudobala** [comment]
@rjkip oh ok, I thought I was missing something :smiley: 

I must say I am very impressed with the awesome work you guys have put into this package.
Took me just a few days to have everything working. And integration with Elastic Search was a breeze.

I will try and contribute back to this project. :+1: 

@mbadolato, @Xerkus, @wjzijderveld and @rjkip

**Comment by wjzijderveld** [comment]
Thanks!
