### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by bouke-nederstigt** [qandidate-labs/broadway#222]
Hi,

First of all thanks for creating the Broadway library. It's been very useful for to me so far. 
Unfortunately I've run into an issue when multiple actions are performed on the same aggregate.

```Uncaught PHP Exception Broadway\EventStore\DBALEventStoreException: "" at /var/www/application_2015_10_22__12_46_14/vendor/broadway/broadway/src/Broadway/EventStore/DBALEventStoreException.php line 23 {"exception":"[object] (Broadway\\EventStore\\DBALEventStoreException(code: 0): at /var/www/application_2015_10_22__12_46_14/vendor/broadway/broadway/src/Broadway/EventStore/DBALEventStoreException.php:23, Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO events (uuid, playhead, metadata, payload, recorded_on, type) VALUES (?, ?, ?, ?, ?, ?)' with params```

I suppose the error is caused because multiple instances try to save their newly created events to the event store, but I don't really have an idea on how to deal with this issue. Any help would be greatly appreciated. It is key for our system that multiple clients can perform actions on the same aggregate.

Regards, Bouke

**Comment by wjzijderveld** [comment]
Order of events is really important with event sourcing, that is why the order is determined by the application. Each time you load an aggregate and record an event, it will use the next position (the playhead).
So if 2 events are recorded at the same time, they both use the same playhead, causing your Exception.

This is something your application has to account for, as Broadway won't be able to determine what to do with the event. So your application has to determine what needs to happen when something fails to be saved to the event store.
Depending on your domain and aggregate there are different solutions.
- Simply inform the client something went wrong and let them try again
- Reload the aggregate and try again (the reloading is important, as you need to have the latest state of the aggregate again).
- Something more fancy that is related to your domain (maybe you need to execute a complete different action on this (or another) aggregate to counteract this)

**Comment by bouke-nederstigt** [comment]
Thanks for the quick reply. I was thinking about retrying as well. Although it won't work in all of my cases, I can probably fail or retry depending on the situation.
