### ISSUE TITLE
Is there a way to retrieve recorded_on into a projection ?

### ISSUE THREAD

**Issue by manelephant** [qandidate-labs/broadway#223]
I am trying to retrieve in my projector the recorded_on event property automatically added by BroadwayBundle to each event.

Any idea on what is the best way to do it ?

Thanx in advance !

**Comment by rjkip** [comment]
@manelephant, if you extend Projector, you receive a DomainMessage as second parameter to your projector method. [See here](https://github.com/qandidate-labs/broadway/blob/d0a4f39b220510715dde818a04a7de6f3b550bc2/src/Broadway/ReadModel/Projector.php#L33)

**Comment by wjzijderveld** [comment]
What he said :smile:

**Comment by manelephant** [comment]
Thank you so much it works !
