### ISSUE TITLE
Searching events for a payload value ?

### ISSUE THREAD

**Issue by manelephant** [qandidate-labs/broadway#224]
Hello,

What is the best practice if i want to search a certain type of event for a specific payload value ?

I need to verify that a payload value is unique before recording the event.

For now i am querying the readModel but it doesn't seem adequate due to the eventual consistency of the read model.

Thanxxx

**Comment by ltouro** [comment]
It seems you got a constraint on your domain that needs to be checked while a command is being handled. I think this is a responsability of an Aggregate: Keep track of previous events and make sure that all invariants are complied.

**Comment by wjzijderveld** [comment]
In my opinion this is not something you should be needing in most cases.
In some cases I think it's fine to use the read models when triggering an action, as the user uses the same read models, so it might be closer to what the user expected.
But in most cases, it's your aggregate that should guard it's state and consistency.

Without more info about your problem area and domain it's hard to give a more precise answer.

**Comment by manelephant** [comment]
Thank for the responses.

It still seems to me that according to ES principles the only truth is in the eventstore.

So in a way or another i'll have to search the eventstore for a given value at the "decide" level.

My Aggregate is pretty simple. Its a "CreditCard" aggregate with events like : 

- CardCreated
- CardEnabled
- CardCredited
- CardDebited
- CardExpirationDateWasChanged

What i need is to be shure a "CardCreated" event can't be made if provided CardNumber already exists somewhere in another card.

For now i am querying the read database to make that happen but i am not totally confortable with that.

**Comment by manelephant** [comment]
Ok maybe not the best place to ask that question http://stackoverflow.com/questions/31386244/cqrs-event-sourcing-check-username-is-unique-or-not-from-eventstore-while-sendin
