### ISSUE TITLE
Finding read model projection row when key is not in event?

### ISSUE THREAD

**Issue by manelephant** [qandidate-labs/broadway#235]
When using the Projector class : How is it possible to access, from a given event, a payload data which is in a previous event of my aggregate ? Or maybe retrieve the final state of my aggregate inside the projector "apply${MyEvent}" method.

I am asking the question here cause i had no luck on stackoverflow.

My root aggregate is a Car.

- First event is a CarCreated event holding the "manufacturer"

- Then i shall have a CarRepaired event with only a "date" as a payload

My new read projection is a CarsRepairedPerManufacturer which will count repaired cars for each manufacturer :

- No problem for the CarCreated event : This event hold de "manufacturer" so my read view is created with the correct key

- The problem is with my CarRepaired event : How can find the correct row (where the key is the manufacturer) in my read model (with the getReadModel function) when i don't have this information in my event ?

Maybe i am missing something here because if this was unsolvable it would limit the kind of projections you could do in ES/CQRS.

**Comment by manelephant** [comment]
Ok sorry for that...it seems i just need to set with the getId() function

**Comment by ltouro** [comment]
@manelephant Make Car Aggregate track its own Manufacturer, add this property to the CarRepaired  event and have the aggregate supply it when applying the event to itself, probably after command handler has issued the $aggregate->repair() method.
