### ISSUE TITLE
Adding gitter.im for support questions

### ISSUE THREAD

**Issue by Konafets** [qandidate-labs/broadway#243]
Hi,

I am currently using Broadway and while the behaviour is good documented by the test cases I am missing some support forum for the application. I am aware of DDD/CQRS and DDDinPHP groups on Google Groups but sometimes I have question especially for Broadway. So including a chat right here to GitHub sounds like a nice idea to solve this.

The Chat in question is https://gitter.im/

**Comment by casvannoort** [comment]
+1

**Comment by wjzijderveld** [comment]
There is the IRC channel which is mentioned in the readme

> Feel free to join #qandidate on freenode with questions and remarks!

I personally don't feel much for yet another communication channel I need to pay attention to.

**Comment by Konafets** [comment]
Its 2016 and you still hang out in IRC channels oO?

**Comment by machwatt** [comment]
![](http://cdn.meme.am/instances/400x/52529111.jpg)
