### ISSUE TITLE
ElasticSearchRepository : Adding 'type' to query and search ?

### ISSUE THREAD

**Issue by manelephant** [qandidate-labs/broadway#246]
Hello Quandidate,

Before making a PR : Wouldn't it be useful to add 'type' => $this->class to both the query and search functions in ElasticSearchRepository ?

My application use multiple types inside the same index (one app => one index => multiple types). And sadly i cannot directly use the methods findBy or find in ElasticSearchRepository because they lack a 'type' constraint.

I there a good reason why its not there ? If not could i make a PR for this ?

Thanx :p #

**Comment by wjzijderveld** [comment]
Hi,

I'm not sure, but I can't imagine it was left out on purpose. So it would make sense to add them in the query method. Also as we do already use it in the find queries.
So a PR would be appreciated :smile: 

<sub>PS. It's Qandidate, not Quandidate :wink:</sub>

**Comment by manelephant** [comment]
Thanx PR done :+1:
