### ISSUE TITLE
Allow to pass timezone 

### ISSUE THREAD

**Issue by szymanskilukasz** [qandidate-labs/broadway#261]
Hey guys,

thanks for great lib. Right now there is an hardcoded timezone for UTC which is not valid for all countries, so it would be great to allow passing custom timezone as parameter, if you don't want to rely on server settings. 

I will send PR for this shortly. Thanks.

**Comment by szymanskilukasz** [comment]
PR #262

**Comment by szymanskilukasz** [comment]
Unfortunately there is an issue with this 

https://github.com/qandidate-labs/broadway/blob/master/src/Broadway/Domain/DateTime.php#L41

Timezone in this case is ignored 

> The timezone parameter and the current timezone are ignored when the time parameter either contains a UNIX timestamp (e.g. 946684800) or specifies a timezone (e.g. 2010-01-28T15:00:00+02:00).

source: http://php.net/manual/pl/datetime.createfromformat.php

So even if we pass it, it doesn't solve this case. Do we need to use createFromFormat? Maybe you guys have some idea how to allow using custom timezone? Thanks

**Comment by asm89** [comment]
> Timezone in this case is ignored

Interesting. What does the timezone end up being?

**Comment by asm89** [comment]
```
$ ~ $ php -r "var_dump(DateTime::createFromFormat('U.u', sprintf('%.6F', microtime(true)))->getTimezone());"
object(DateTimeZone)#2 (2) {
  ["timezone_type"]=>
  int(1)
  ["timezone"]=>
  string(6) "+00:00"
}
```

Aha. :) "+00:00" is still fine, because we want to store the dates "timezone agnostic". If you're using the timing data etc from the event store for displaying purposes you should convert the dates to the appropriate TZ.

**Comment by szymanskilukasz** [comment]
@asm89 Hey, thanks for reply, just figure out other solution.

I have implemented my own EventStore (cause I am not using DBAL) so in this case you can modify this line 

https://github.com/qandidate-labs/broadway/blob/master/src/Broadway/EventStore/DBALEventStore.php#L127

For something like this

```php
(new \DateTime($domainMessage->getRecordedOn()->toString()))
    ->setTimezone(new \DateTimeZone("Europe/Warsaw"))
    ->format('Y-m-d\TH:i:s.uP')
```

So yeah, if you want to keep timezone agnostic code this can be solution for workaround. 

Thanks :)
