### ISSUE TITLE
Retrieving events from event store

### ISSUE THREAD

**Issue by moleculezz** [qandidate-labs/broadway#271]
Hi,

It seems to me that you can't retrieve the log of events from the event store.
Use case for that is to display an audit trail or just a history of changes that were made to an aggregate root. `Event Store` by Greg Young seems to have this capability according to him.

perhaps `Broadway\EventSourcing\EventSourcingRepository` would benefit from a function `getEvents()` or `getDomainEventStream()`.

```php
/**
 *
 * @return DomainEventStream
**/
public function getEvents($id)
{
    return $this->eventStore->load($id);
}
```

I'm no expert in Event Sourcing so I don't know what kind of effect this would have on the rest of broadway, but if `Broadway\EventStore\DBALEventStore::load($id)` method returns a `DomainEventStream` why doesn't the `EventSourcingRepository` return the same?

**Comment by mdwheele** [comment]
The role of an aggregate repository is to load and persist aggregate instances. That's a reason you wouldn't see that method on the repository interface. 

What keeps you from querying the event store directly or registering an event listener or projection to take care of your auditing needs? In general, it can be a bad idea to expose the event store for one bounded context to another, directly. In many cases a projection of the event store is more appropriate. Logging is an excellent example here.

**Comment by moleculezz** [comment]
Makes sense what you are saying. An aggregate should not need to know how it was built up.
I thought about making a new projection, but it seems weird to have a duplicate of the event store in the read model.

Thanks for the tips, I'll look into both solutions.
