### ISSUE TITLE
The bundle should not hardcode the name of the DB connection

### ISSUE THREAD

**Issue by stof** [qandidate-labs/broadway#3]
In the bundle, the name ``default`` is hardcoded in several places using the connection.

But there is no guarantee that a connection named ``default`` will exist (or that it is the default one). DoctrineBundle does not give such guarantee (``default`` is just the name used by the short syntax).

**Comment by cordoval** [comment]
why not #137  is merged? cough cough, "any chance of having #137 in?"

:older_man: learning to ask :+1:
