### ISSUE TITLE
[Suggestion] Common base exception class or interface

### ISSUE THREAD

**Issue by Miliooo** [qandidate-labs/broadway#46]
It would be nice if all exceptions thrown had a common base, so something like this is possible to catch all exceptions from Broadway.

```
try {
    // some code here
} catch (\Broadway\Exception\BaseException $e) {
    //do something here, logging etc
}
```

**Comment by asm89** [comment]
Closing this. I don't see us doing this any time soon. Maybe per component when we start splitting everything up.
