### ISSUE TITLE
Provide an example for a saga

### ISSUE THREAD

**Issue by bluescreen** [qandidate-labs/broadway#67]
It would be very helpful to provide a simple example for sagas. 
I'm just trying to figure out how this works. Thanks!

**Comment by F21** [comment]
:+1:

**Comment by jaymecd** [comment]
:+1:

**Comment by psamatt** [comment]
:+1:

**Comment by danizord** [comment]
:+1:

**Comment by ricfrank** [comment]
:+1:

**Comment by francescotrucchia** [comment]
:+1:

**Comment by matthiasnoback** [comment]
For anyone who's interested: I'm hoping to fix this as part of https://github.com/qandidate-labs/broadway/pull/185

**Comment by matthiasnoback** [comment]
This one can be closed I guess.

**Comment by asm89** [comment]
@matthiasnoback Yes!

See https://github.com/qandidate-labs/broadway/tree/a5a40d700f323a43ff39b075d5b94507a763544e/examples/saga.
